### PR TITLE
Advanced tab fixes

### LINKED ISSUE #361: Hardware preset dropdown is not working
I've created `Max` preset with all values set to maximum.

```
$ sqlite3 /Users/tworec/Library/Application\ Support/golem/default/mainnet/golem.db -cmd 'select * from hardwarepreset'
1|2018-04-09 08:20:06.508649|2018-04-09 08:20:06.508650|default|7|25165824|413915608
2|2018-04-09 08:20:06.510322|2018-04-09 08:20:06.510323|custom|3|3145728|20971520
3|2018-06-04 13:47:24.810067|2018-06-04 13:47:24.810074|max|7|104857600|1048576000
4|2018-06-04 13:48:05.883941|2018-06-04 13:48:05.883949|2rec|5|3145728|20971520
```

After selecting it, presets stays at previous positions eg.

screen shot 2018-06-04 at 13 52 21

golem-electron ver b73b859
golem ver golemfactory/golem@7a63ea909

### LINKED ISSUE #366: advanced resources tab is not working
Everything is zero-ed.

image

### PR DESCRIPTION
**Pull request by mdtanrikulu**
Resolves #366.
Resolves #361.

- Advanced tab initial chart value fixed
- Hardware preset dropdown issue fixed

### CODE REVIEW

File: src/components/network/tabs/Advanced.js [hunk 1]
```diff
@@ -71,7 +81,7 @@ export class Advanced extends React.Component {
      */
     _handleOptionChange(list, selectedIndex, init = false) {
         const {actions, chartValues} = this.props
-        let value = list[selectedIndex]
+        const value = list.find(item => item.name === selectedIndex);
```
Comment (tworec) [inline src/components/network/tabs/Advanced.js:84]: it is veeery bad to compare name with index, isn't it? ;)

Comment (mdtanrikulu) [reply src/components/network/tabs/Advanced.js:84]: I mimicked old code to do quick fix, but yeap it is. Will need to be changed with proper variable later.

Comment (tworec) [reply src/components/network/tabs/Advanced.js:84]: such quick dirty fixes tend to wonder around for lot of time. Adding TODO in code is a minimum, to inform future reader why you had written such a thing ;)

Even better is to fill an self-issue for this.
