### PR TITLE
Log path changed as default golem log path

### LINKED ISSUE #234: Log location not found on 0.1.7
From public chat, someone started the app on macos and saw this error:

golem-javascript-error

I think the logs should move to next to the golem logs:

https://github.com/golemfactory/golem/wiki/Testing#where-are-the-logs

### PR DESCRIPTION
**Pull request by mdtanrikulu**
Resolves #234 
@see: https://github.com/golemfactory/golem/wiki/Testing#where-are-the-logs

### CODE REVIEW

File: electron/debug_handler.js [hunk 1]
```diff
@@ -24,17 +24,34 @@ const level = Object.freeze({
     SILLY: 'silly'
 })
 
+let LOGPATH;
+
+switch(os.platform()){
+    case "win32":
+        LOGPATH = `${HOMEDIR}\\AppData\\golem\\golem\\default\\logs\\`
```
Comment (maaktweluit) [inline electron/debug_handler.js]: Missing `Local` here: `AppData\Local\golem`

**Review by maaktweluit — COMMENTED** [review]
LGTM!

Missing one folder in the windows version

Maybe also update the readme? it can link to the wiki page in the PR description
