### PR TITLE
Run benchmarks on every start

### LINKED ISSUE #346: performance not recalculating after resources (CPU, RAM) reallocation
change to CPU cores allocation impacts node's performance, but now change CPU cores or RAM will not trigger performance recalculation. This leads to wrong perception of node as a provider.

needs to be fixed before golemfactory/golem#2771

### PR DESCRIPTION
**Pull request by tworec**
`activatePreset` saga to accept performance values.
Benchmarks are triggered only when hw config is changed (checks on python side).
When benchamarks are executed GUI is shaded, but clicking on Tasks or settings icon and back to Network removes shade.

fixes #346 
works only with golemfactory/golem#2798

### CODE REVIEW

File: src/sagas/engine.js [hunk 1]
```diff
@@ -41,15 +46,20 @@ export function activatePreset(session, payload) {
...
     const engineStatus = yield call(fireEngine, session);
     //console.log(engineStatus)
+    console.log('golemizeBase: fireEngine: ' + engineStatus)
     if (!engineStatus) {
         yield put({
             type: SET_GOLEM_PAUSE_STATUS,
             payload: true
         })
+    } else {
+        yield action && put(action)
```
Comment (tworec) [inline src/sagas/engine.js]: I don't know how to invoke `GET_PERFORMANCE_CHARTS` after node is started, because both rpc's above are returning immediately

**Review by mdtanrikulu — APPROVED** [review]
